module StudyCatalog

using ..StudyCore

export available_studies,
       implemented_studies,
       planned_studies,
       prototype_studies,
       legacy_reference_studies,
       studies_by_status,
       studies_by_domain

const STUDIES = [
    StudyDescriptor(:emt, "Electromagnetic transient", :dynamic, :implemented, "src/julia/studies/emt.jl"),
    StudyDescriptor(:power_flow, "AC balanced power flow", :static, :planned, "src/julia/studies/power_flow.jl"),
    StudyDescriptor(:unbalanced_power_flow, "AC unbalanced multiphase power flow", :static, :planned, "planned"),
    StudyDescriptor(:dc_power_flow, "DC power flow", :static, :planned, "planned"),
    StudyDescriptor(:voltage_drop, "Voltage drop", :static, :planned, "planned"),
    StudyDescriptor(:load_allocation, "Load allocation", :static, :planned, "planned"),
    StudyDescriptor(:load_growth, "Load growth and planning", :planning, :planned, "planned"),
    StudyDescriptor(:contingency, "Contingency and N-1 screening", :planning, :planned, "planned"),
    StudyDescriptor(:voltage_stability, "Voltage stability margin", :static, :planned, "planned"),
    StudyDescriptor(:hosting_capacity, "DER hosting capacity", :planning, :planned, "planned"),
    StudyDescriptor(:optimal_power_flow, "Optimal power flow", :optimization, :planned, "planned"),
    StudyDescriptor(:short_circuit, "Short circuit", :static, :planned, "src/julia/studies/short_circuit.jl"),
    StudyDescriptor(:iec_short_circuit, "IEC-style short circuit", :fault, :planned, "planned"),
    StudyDescriptor(:ansi_short_circuit, "ANSI-style short circuit", :fault, :planned, "planned"),
    StudyDescriptor(:unbalanced_fault, "Unbalanced fault analysis", :fault, :planned, "planned"),
    StudyDescriptor(:dc_short_circuit, "DC short circuit", :fault, :planned, "planned"),
    StudyDescriptor(:protection, "Protection coordination", :protection, :planned, "src/julia/studies/protection.jl"),
    StudyDescriptor(:relay_settings, "Relay setting calculation", :protection, :planned, "planned"),
    StudyDescriptor(:time_current_coordination, "Time-current coordination", :protection, :planned, "planned"),
    StudyDescriptor(:fuse_recloser_coordination, "Fuse and recloser coordination", :protection, :planned, "planned"),
    StudyDescriptor(:distance_protection, "Distance protection", :protection, :planned, "planned"),
    StudyDescriptor(:differential_protection, "Differential protection", :protection, :planned, "planned"),
    StudyDescriptor(:protection_optimization, "Protection setting optimization", :optimization, :planned, "planned"),
    StudyDescriptor(:arc_flash, "Arc flash", :safety, :planned, "src/julia/studies/arc_flash.jl"),
    StudyDescriptor(:arc_flash_labels, "Arc-flash labels", :safety, :planned, "planned"),
    StudyDescriptor(:grounding_grid, "Grounding grid design", :safety, :planned, "planned"),
    StudyDescriptor(:step_touch_voltage, "Step and touch voltage", :safety, :planned, "planned"),
    StudyDescriptor(:grounding_conductor_sizing, "Grounding conductor sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:lightning_surge_risk, "Lightning and surge risk screening", :safety, :planned, "planned"),
    StudyDescriptor(:rms_transient_stability, "RMS transient stability", :dynamic, :planned, "planned"),
    StudyDescriptor(:switching_transients, "Switching transients", :dynamic, :planned, "planned"),
    StudyDescriptor(:lightning_transients, "Lightning and surge transients", :dynamic, :planned, "planned"),
    StudyDescriptor(:transformer_inrush, "Transformer energization and inrush", :dynamic, :planned, "planned"),
    StudyDescriptor(:motor_starting_dynamic, "Motor starting dynamics", :machines, :planned, "planned"),
    StudyDescriptor(:ferroresonance, "Ferroresonance", :dynamic, :planned, "planned"),
    StudyDescriptor(:insulation_coordination, "Insulation coordination", :safety, :planned, "planned"),
    StudyDescriptor(:harmonic_load_flow, "Harmonic load flow", :power_quality, :planned, "planned"),
    StudyDescriptor(:harmonic_resonance, "Harmonic resonance", :power_quality, :planned, "planned"),
    StudyDescriptor(:filter_sizing, "Harmonic filter sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:flicker, "Flicker", :power_quality, :planned, "planned"),
    StudyDescriptor(:voltage_sag_swell, "Voltage sag and swell", :power_quality, :planned, "planned"),
    StudyDescriptor(:voltage_unbalance, "Voltage unbalance", :power_quality, :planned, "planned"),
    StudyDescriptor(:induction_machine, "Induction machine model", :machines, :planned, "planned"),
    StudyDescriptor(:synchronous_machine, "Synchronous machine model", :machines, :planned, "planned"),
    StudyDescriptor(:generator_capability, "Generator capability and loading", :machines, :planned, "planned"),
    StudyDescriptor(:motor_torque_speed, "Motor torque-speed checks", :machines, :planned, "planned"),
    StudyDescriptor(:machine_thermal, "Machine thermal loading", :machines, :planned, "planned"),
    StudyDescriptor(:excitation_governor, "Excitation and governor models", :machines, :planned, "planned"),
    StudyDescriptor(:pv_string_sizing, "PV string sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:pv_inverter_sizing, "PV inverter sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:pv_cable_sizing, "PV DC and AC cable sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:pv_yield, "PV yield and clipping", :renewables, :planned, "planned"),
    StudyDescriptor(:grid_following_inverter, "Grid-following inverter model", :power_electronics, :planned, "planned"),
    StudyDescriptor(:grid_forming_inverter, "Grid-forming inverter model", :power_electronics, :planned, "planned"),
    StudyDescriptor(:bess_sizing, "Battery energy storage sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:storage_dispatch, "Storage dispatch", :optimization, :planned, "planned"),
    StudyDescriptor(:wind_turbine, "Wind turbine model", :renewables, :planned, "planned"),
    StudyDescriptor(:ride_through, "Ride-through compliance checks", :power_electronics, :planned, "planned"),
    StudyDescriptor(:cable_ampacity, "Cable ampacity", :thermal, :planned, "planned"),
    StudyDescriptor(:dynamic_cable_rating, "Dynamic cable thermal rating", :thermal, :planned, "planned"),
    StudyDescriptor(:cable_thermal_capacity, "Cable thermal overload capacity", :thermal, :planned, "planned"),
    StudyDescriptor(:cable_short_circuit_withstand, "Cable short-circuit withstand", :thermal, :planned, "planned"),
    StudyDescriptor(:cable_pulling, "Cable pulling and tension checks", :mechanical, :planned, "planned"),
    StudyDescriptor(:duct_bank_derating, "Duct-bank and tray derating", :thermal, :planned, "planned"),
    StudyDescriptor(:line_constants, "Overhead line impedance and capacitance constants", :lines, :implemented, "src/julia/studies/line_constants.jl"),
    StudyDescriptor(:cable_constants, "Cable constants and frequency scan", :lines, :implemented, "src/julia/studies/cable_constants.jl"),
    StudyDescriptor(:sheath_bonding, "Cable sheath bonding and circulating current", :lines, :planned, "planned"),
    StudyDescriptor(:conductor_sizing, "Conductor sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:transformer_sizing, "Transformer sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:generator_sizing, "Generator sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:motor_sizing, "Motor sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:switchgear_rating, "Switchgear rating", :sizing, :planned, "planned"),
    StudyDescriptor(:ct_vt_sizing, "CT and VT sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:ups_battery_sizing, "UPS and battery sizing", :sizing, :planned, "planned"),
    StudyDescriptor(:feeder_reconfiguration, "Feeder reconfiguration", :optimization, :planned, "planned"),
    StudyDescriptor(:capacitor_placement, "Capacitor placement optimization", :optimization, :planned, "planned"),
    StudyDescriptor(:der_placement_sizing, "DER placement and sizing", :optimization, :planned, "planned"),
    StudyDescriptor(:cable_sizing_optimization, "Cable sizing optimization", :optimization, :planned, "planned"),
    StudyDescriptor(:reliability_indices, "Reliability indices", :reliability, :planned, "planned"),
    StudyDescriptor(:outage_impact, "Outage impact", :reliability, :planned, "planned"),
    StudyDescriptor(:asset_aging, "Asset loading and aging", :reliability, :planned, "planned"),
    StudyDescriptor(:transformer_loss_of_life, "Transformer loss-of-life", :reliability, :planned, "planned"),
    StudyDescriptor(:cable_thermal_aging, "Cable thermal aging", :reliability, :planned, "planned"),
]

available_studies() = copy(STUDIES)
studies_by_status(status::Symbol) = filter(study -> study.status == status, STUDIES)
implemented_studies() = studies_by_status(:implemented)
planned_studies() = studies_by_status(:planned)
prototype_studies() = studies_by_status(:prototype)
legacy_reference_studies() = studies_by_status(:legacy_reference)
studies_by_domain(domain::Symbol) = filter(study -> study.domain == domain, STUDIES)

end
